#Problem2
"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def fibnonacci(n):
    if n==0 or n==1:
        return 1
    elif n>=2:
        return fibnonacci(n-1)+fibnonacci(n-2)
answer=0
n=0
while fibnonacci(n)<=4000000:
    if fibnonacci(n)%2==0:
        answer=fibnonacci(n)+answer
        n=n+1
    else:
        n=n+1

print(answer)





