#P45
"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	T_n=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	P_n=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	H_n=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T_285 = P_165 = H_143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""
n = 144
Num = n * (2 * n - 1)
T_n = (-1 +(1 + 8 * Num) ** 0.5) / 2
P_n = (1 + (1 + 24 * Num) ** 0.5) / 6
while T_n % 1 != 0 or P_n % 1 != 0 :
    n += 1
    Num = n * (2 * n - 1)
    T_n = (-1 + (1 + 8 * Num) ** 0.5) / 2
    P_n = (1 + (1 + 24 * Num) ** 0.5) / 6
print(Num)
